export const EXECUTION_CONFIG_LOAD = 'EXECUTION_CONFIG_LOAD'
export const EXECUTION_CONFIG_LOAD_SUCCESS = 'EXECUTION_CONFIG_LOAD_SUCCESS'
export const EXECUTION_CONFIG_LOAD_ERROR = 'EXECUTION_CONFIG_LOAD_ERROR'

export const EXECUTION_PREPROCESS_DATASET = 'EXECUTION_PREPROCESS_DATASET'
export const EXECUTION_PREPROCESS_DATASET_SUCCESS = 'EXECUTION_PREPROCESS_DATASET_SUCCESS'
export const EXECUTION_PREPROCESS_DATASET_ERROR = 'EXECUTION_PREPROCESS_DATASET_ERROR'
export const EXECUTION_PREPROCESS_DATASET_SCHEDULED = 'EXECUTION_PREPROCESS_DATASET_SCHEDULED'
export const EXECUTION_PREPROCESS_DATASET_FINISHED = 'EXECUTION_PREPROCESS_DATASET_FINISHED'
export const EXECUTION_PREPROCESS_DATASET_FETCHED = 'EXECUTION_PREPROCESS_DATASET_FETCHED'

export function preprocessDataset({ dataset, pipeline, version }) {
  return {
    type: EXECUTION_PREPROCESS_DATASET,
    dataset, pipeline, version
  }
}