export {
  DeviceHub as PipelineIcon,
  Accessibility as SubjectIcon,
  ExpandMore as ExpandMoreIcon,
  MoreVert as MoreVertIcon,
  OpenInNew as OpenIcon,
  Launch as LaunchIcon,
  RemoveCircle as RemoveIcon,
  NavigateNext as NavigateNextIcon,
  Settings as SettingsIcon,
  DeveloperBoard as EnvironmentIcon,
  PlayCircleFilled as RunIcon,
  Folder as ProjectIcon,
  FolderOpen as ProjectOpenIcon,
  MenuIcon as Menu,

  LoadingIcon as Loop,
  AuthErrorIcon as Lock,
  ErrorIcon as Error,
  DoneIcon as Done,
} from 'material-ui-icons';
